# 주석은 똑같다.
mybatis:
  mapper-locations: mappers/**/*.xml


spring:
  application:
    name: madang

  datasource:
    url: jdbc:mariadb://localhost/madang_spring
    username: root
    password: green502

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    default-models-expand-depth: -1
    path: /swagger
